{{- if .Values.haproxy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy-template-ic.fullname" . }}-haproxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haproxy-template-ic.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
  {{- with .Values.haproxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.haproxy.service.type }}
  selector:
    {{- include "haproxy-template-ic.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
  ports:
    - name: http
      port: {{ .Values.haproxy.service.http.port }}
      targetPort: {{ .Values.haproxy.service.http.targetPort }}
      protocol: TCP
      {{- if eq .Values.haproxy.service.type "NodePort" }}
      nodePort: {{ .Values.haproxy.service.http.nodePort }}
      {{- end }}
    - name: https
      port: {{ .Values.haproxy.service.https.port }}
      targetPort: {{ .Values.haproxy.service.https.targetPort }}
      protocol: TCP
      {{- if eq .Values.haproxy.service.type "NodePort" }}
      nodePort: {{ .Values.haproxy.service.https.nodePort }}
      {{- end }}
    - name: stats
      port: {{ .Values.haproxy.service.stats.port }}
      targetPort: {{ .Values.haproxy.service.stats.targetPort }}
      protocol: TCP
      {{- if eq .Values.haproxy.service.type "NodePort" }}
      nodePort: {{ .Values.haproxy.service.stats.nodePort }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy-template-ic.fullname" . }}-haproxy-dataplane
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haproxy-template-ic.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
spec:
  type: {{ .Values.haproxy.dataplane.service.type }}
  selector:
    {{- include "haproxy-template-ic.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
  ports:
    - name: dataplane
      port: {{ .Values.haproxy.dataplane.service.port }}
      targetPort: 5555
      protocol: TCP
{{- end }}
