apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy-template-ic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "haproxy-template-ic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.controller.ports.healthz }}
      targetPort: healthz
      protocol: TCP
      name: healthz
    - port: {{ .Values.controller.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "haproxy-template-ic.selectorLabels" . | nindent 4 }}
