apiVersion: v2
name: haproxy-template-ic
description: HAProxy Template Ingress Controller
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - haproxy
  - ingress
  - controller
  - loadbalancer
  - template
home: https://github.com/phihos/haproxy-template-ingress-controller
sources:
  - https://github.com/phihos/haproxy-template-ingress-controller
maintainers:
  - name: phihos
