apiVersion: v2
name: haproxy-template-ic
description: HAProxy Template Ingress Controller
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - haproxy
  - ingress
  - controller
  - loadbalancer
  - template
home: https://github.com/phihos/haproxy-template-ingress-controller
sources:
  - https://github.com/phihos/haproxy-template-ingress-controller
maintainers:
  - name: phihos
annotations:
  # Document all component images (Artifact Hub standard)
  images: |
    - name: controller
      image: ghcr.io/phihos/haproxy-template-ic:0.1.0
    - name: haproxy
      image: haproxytech/haproxy-debian:3.2
  # Minimum HAProxy version requirement
  haproxy.org/minimum-version: "3.0"
